project_id = "wvqqoigrslatxnbykcji"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.import-products-csv]
    verify_jwt = false
  [functions.send-onboarding-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
